import type { Metadata } from "next";
import { PageContainer, PageHeader } from "@/components/app/page-header";
import { RoadmapTimeline } from "@/components/roadmap/roadmap-timeline";

export const metadata: Metadata = {
  title: "Roadmap",
  description: "Your AI-generated, month-by-month admissions roadmap with milestones and tasks.",
};

export default function RoadmapPage() {
  return (
    <PageContainer>
      <PageHeader
        title="Your Roadmap"
        description="A personalized, month-by-month plan from today to acceptance — generated by AI and tailored to your target intake."
      />
      <div className="mt-7">
        <RoadmapTimeline />
      </div>
    </PageContainer>
  );
}
